### ISSUE TITLE
Don't hardcode ido

### ISSUE THREAD

**Issue by rootzlevel** [the-kenny/weechat.el#29]
`weechat--read-channel-name` automatically uses ido, if it's available. I'd prefer a customization option, since I use another completion system.

**Comment by the-kenny** [comment]
Hans-Peter Deifel <notifications@github.com> writes:

> `weechat--read-channel-name` automatically uses ido, if it's available. I'd prefer a customization option, since I use another completion system.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/the-kenny/weechat.el/issues/29

Thanks for this request. I'll add this later this week.
