### ISSUE TITLE
About completing downcased usernames

### ISSUE THREAD

**Issue by rootzlevel** [the-kenny/weechat.el#32]
I've seen the commit that introduced this, so it's intentional. But I really don't see the point. I want to write the nick of people the way they chose them and not in lowercase form (which suggests that I'm too lazy to spell their name correctly).

It would be nice if lowercase letters could complete the uppercase name: Typing `n`<kbd>TAB</kbd> should result in `Nick`, not `nick`. But in absence of that: Please consider not downcasing the names. (At least make it configurable).

**Comment by the-kenny** [comment]
Pushed a commit disabling downcasing.

I implemented this as ```pcomplete-ignore-case``` didn't seem to work. Setting ```completion-ignore-case``` to ```t``` works just like you expect.
