### ISSUE TITLE
Try to require auth-source in weechat-password-auth-source-callback

### ISSUE THREAD

**Issue by hpdeifel** [the-kenny/weechat.el#36]
Instead of just using `(fboundp 'auth-source-search)`, it would be nice if `auth-source` would actually be required beforehand. Otherwise, the function might not be bound, although `auth-source` is actually available.

I haven't done a pull request on this, since I'm not sure if the current behaviour is intentional.

**Comment by the-kenny** [comment]
This is intentional so we don't force the user to load ```auth-source```. 

Actually, ```weechat-password-callback``` should default to ```nil``` so we don't load anything from ```.authinfo``` if the user hasn't explicitly enabled it. (Preferable, as people might encrypt their ```.authinfo``` via GnuPG which emacs would automatically try to decrypt)
