### ISSUE TITLE
Add "Fetch more lines" for buffers

### ISSUE THREAD

**Issue by jmacdonagh** [the-kenny/weechat.el#44]
It would be nice if weechat.el could fetch a limited number of lines when a buffer is monitored, but then allow the user to fetch previous lines on command. [glowing-bear](https://github.com/glowing-bear/glowing-bear) does this and it seems to work pretty well. The user can specify a small number of initial lines to grab when a buffer is monitored and decide to get more if they feel they missed something.

**Comment by jmacdonagh** [comment]
Rather than demand things from you I decided to try and implement it myself. Check out PR #45.

**Comment by bricewge** [comment]
This issue can be closed since the pull request #45 has been merged.

**Comment by the-kenny** [comment]
Thanks for the reminder!
