### ISSUE TITLE
"error in process filter" in the latest version

### ISSUE THREAD

**Issue by pmiddend** [the-kenny/weechat.el#49]
After upgrading from melpa to version 20160226.1210, in regular intervals I get the error following message in the minibuffer and the messages buffer:

    error in process filter: save-current-buffer: Wrong type argument: stringp, nil
    error in process filter: Wrong type argument: stringp, nil

**Comment by the-kenny** [comment]
Is this still relevant? I don't see it on my setup.

**Comment by pmiddend** [comment]
Sorry, I didn't update the issue. Doesn't appear here anymore.
