### ISSUE TITLE
weechat.el interferes with gnutls in the newest Emacs builds

### ISSUE THREAD

**Issue by TeMPOraL** [the-kenny/weechat.el#50]
Hi there,

I've been having issues with Emacs package manager that I tracked down to being caused by the advice weechat-relay.el sets. It breaks the package loading process, making you unable to update packages.

I've tracked it down to the change introduced on 31st of January:

https://github.com/emacs-mirror/emacs/commit/0f47153b97ae31b82366a857ec2f937c1580b637#diff-5d7e56c028ab4532a94bfbb6710606b5

This change added an optional parameter to the function `open-gnutls-stream`.

To work around it, I updated the advice in weechat-relay.el to look like this:

```
(defun weechat--relay-open-gnutls-stream (name buffer host service &optional nowait)
  "Just like `open-gnutls-stream' with added validation."
  (require 'gnutls)
  (gnutls-negotiate
   :process (weechat--relay-open-socket name buffer host service)
   :type 'gnutls-x509pki
   :hostname host
   :verify-error weechat-relay-ssl-check-signatures))

(defadvice open-gnutls-stream (around weechat-verifying
                                      (name buffer host service &optional nowait))
  (setq ad-return-value
        (weechat--relay-open-gnutls-stream name buffer host service)))
```

Note the additional `&optional nowait` parameter.

I've also removed the `:verify-hostname-error` parameter because according to the docstring of `gnutls-boot-parameters`, it is a "backwards compatibility option for putting :hostname in VERIFY-ERROR". Passing it as `t` with also passing `t` to `:verify-error` caused another error (somehow the returned gnutls boot parameters had a `:verify-error (:hostname . t)` entry which was not `listp`.

This solves the issue completely, as far as I could tell.

Note that this issue is relevant only to the most recent compilations of Emacs 25. In particular, I'm running:

GNU Emacs 25.1.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) of 2016-04-23

(i.e. I built it few hours ago).

I'm leaving it here a) for people who are also running a bleeding-edge Emacs copy, and b) so that it'll be easier for you to update whenever you decide it's time to start supporting the new changes.

**Comment by the-kenny** [comment]
Whoops! I'm sorry for causing so much trouble with that `advice`. My advice here is: Never monkey-patch stuff :)

Do you happen to know if your changes are backwards compatible with the current emacs release? If so I'd like to merge them and bake a new release.

**Comment by TeMPOraL** [comment]
No problem; it's my choice to stay with the bleeding edge of Emacs development ;). Emacs 25 is technically not released yet, much less 25.1.

Anyway, I haven't tested those changes on 25.0 or below, but I don't expect them to be backwards-compatible - the function signature has changed. Maybe the other change (getting rid of `:verify-hostname-error`) is portable, but I'm not sure. The whole thing *could* probably be wrapped in some sort of version check though.

I'll try to test it on an older Emacs if I have time somewhen next week.

**Comment by the-kenny** [comment]
I can test it myself too. I just asked in case you tried it already. I suppose we'll wait with implementing your changes until there's a stable release of 25.

**Comment by TeMPOraL** [comment]
Sure :). I just thought leaving it here will be helpful for others who encounter this problem when trying out the newest Emacs straight from sources :).

**Comment by the-kenny** [comment]
@TeMPOraL Is this issue still relevant with the final release of 25? I just tried SSL briefly and it seems to work on my machine.

**Comment by methanoliver** [comment]
@the-kenny It is relevant in the current [emacs-snapshot](https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa). I just stepped on it.

This is kind of a pain, now I have to remember to manually patch after installation...

**Comment by kngtani** [comment]
I just encountered the same issue as well.
Verified the workaround resolved the issue.
Hope we can get this implemented.

**Comment by mrvdb** [comment]
The proposed workaround is still needed, perhaps merge it in? Emacs 25 is now pretty common.

**Comment by the-kenny** [comment]
Will do! Sorry for not responding earlier.

**Comment by the-kenny** [comment]
Right now I'm inclined to just remove the advice. In hindsight `weechat.el` shouldn't be responsible for fixing/implementing validation in `gnutls`.

88f8ccf fixes this issue, thanks to @TeMPOraL 

bcf714e removes the advice altogether, moving the responsibility back to `gnutls`

Thanks!
