### ISSUE TITLE
provide weechat-monitor-all-buffers

### ISSUE THREAD

**Issue by sleep-walker** [the-kenny/weechat.el#52]
I'm not sure if I am doing it wrong but I really miss `weechat-monitor-all-buffers`. So far I am adding each one manually. It would be also nice to make possible that new buffers would be monitored automatically as well.

**Comment by sleep-walker** [comment]
The latter seems to be already in `weechat-auto-monitor-new-buffers`.

**Comment by the-kenny** [comment]
Should be an easy change, give me a few minutes

**Comment by the-kenny** [comment]
Added `weechat-monitor-all-buffers` and while at it made `weechat-re-montior-buffers` interactive. Can you try latest master to see if this works for you?

**Comment by sleep-walker** [comment]
`weechat-monitor-all-buffers` work as expected, thanks! I'm can't verify `weechat-re-monitor-buffers` as I don't know the purpose. Re-monitor on reconnect?

**Comment by the-kenny** [comment]
Glad to see it's working for you. `re-monitor` is exactly for this: Auto-re-monitor on reconnect. weechat.el does that automatically by default - I just made it interactive for people who disable this feature and want to do it manually.

**Comment by the-kenny** [comment]
I'll close this issue as it seems to be solved! If you have any other issues, feel free to open more (or drop me an email with comments)
