### ISSUE TITLE
Connecting to 192.168.1.50:9000...  apply: Wrong number of arguments: #[(ad--addoit-function name buffer host service) "ÅÆ	 $)" [ad-return-value name buffer host service nil weechat--relay-open-gnutls-stream] 6], 6

### ISSUE THREAD

**Issue by emacsomancer** [the-kenny/weechat.el#72]
I have a weechat server set up with a self-signed ssl certificate. I've copied the "-----BEGIN CERTIFICATE----- ...." part of it to my local machine, and added it to emacs via: 

````
(use-package gnutls
  :config
  (add-to-list 'gnutls-trustfiles (expand-file-name "~/.emacs.d/weechat-relay.cert")))
````
I've tested that I can connect via https://www.glowing-bear.org from the same machine (after following their instructions about trusting the cert in the browser).

But when I run `weechat-connect` and connect to the same machine, I get the following message:

````
Connecting to 192.168.1.50:9000...  apply: Wrong number of arguments: #[(ad--addoit-function name buffer host service) "ÅÆ	 $)" [ad-return-value name buffer host service nil weechat--relay-open-gnutls-stream] 6], 6
````

I'm sure I'm doing something daft, but I'm not sure what.

**Comment by the-kenny** [comment]
I just pushed the tag `0.5.0` which contains a fix for this issue. It should be available on melpa and melpa-stable in a few hours.

Until then you can install the development snapshot from `melpa` which also includes a fix for this issue.

**Comment by emacsomancer** [comment]
I didn't see any updates ever come through. But I ended up using a Let's Encrypt cert, which resolved the issue (or side-stepped it, at least). I'm not convinced it was really a `weechat-el` issue, as I had the same problem trying to use `erc`.
